### ISSUE TITLE
[2pt] Final Capstone - Kanban Board 

### ISSUE THREAD

**Issue by yigitm** [yigitm/book-appointment#1]
- [Repo Link](https://github.com/yigitm/book-appointment)
- One person : @yigitm

![Screen Shot 2022-04-29 at 02 00 40](https://user-images.githubusercontent.com/24368914/165861353-b4e45551-81f3-46a3-8abd-d7c3f86f23bd.png)

**Comment by MuriloRoque** [comment]
Hi @yigitm,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
